/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function init(appId: number): void
export function runCallbacks(): void
export namespace achievement {
  export function activate(achievement: string): boolean
}
export namespace cloud {
  export function isEnabledForAccount(): boolean
  export function isEnabledForApp(): boolean
  export function readFile(name: string): string
  export function writeFile(name: string, content: string): boolean
  export function deleteFile(name: string): boolean
}
export namespace localplayer {
  export interface LocalSteamId {
    steamId64: string
    steamId32: string
    accountId: number
  }
  export function getSteamId(): LocalSteamId
  export function getName(): string
  export function getLevel(): number
  export function getIpCountry(): string
}
export namespace stats {
  export function getInt(name: string): number | undefined | null
  export function setInt(name: string, value: number): boolean
  export function store(): boolean
  export function resetAll(achievementsToo: boolean): boolean
}
export namespace workshop {
  export interface UgcResult {
    itemId: bigint
    needsToAcceptAgreement: boolean
  }
  export interface UgcUpdate {
    title?: string | undefined | null
    description?: string | undefined | null
    changeNote?: string | undefined | null
    previewPath?: string | undefined | null
    contentPath?: string | undefined | null
    tags?: Array<string> | undefined | null
  }
  export interface InstallInfo {
    folder: string
    sizeOnDisk: bigint
    timestamp: number
  }
  export interface DownloadInfo {
    current: bigint
    total: bigint
  }
  export function createItem(): Promise<UgcResult>
  export function updateItem(itemId: bigint, updateDetails: UgcUpdate): Promise<UgcResult>
  export function subscribe(itemId: bigint): Promise<void>
  export function unsubscribe(itemId: bigint): Promise<void>
  export function state(itemId: bigint): number
  export function installInfo(itemId: bigint): InstallInfo | undefined | null
  export function downloadInfo(itemId: bigint): DownloadInfo | undefined | null
  export function download(itemId: bigint, highPriority: boolean): void
}
